#!/bin/sh
# Generated by blade; do not edit. See backend.py (_inclusion_wrapper_script).
mode=$1
out=$2
shift 2
err=$out.err
export LC_ALL=C
if [ "$mode" = hdrs ]; then
    # -fdirectives-only speeds up preprocessing but breaks on some edge cases
    # (e.g. __COUNTER__ tricks); retry without it, discarding the first
    # attempt's diagnostics.
    "$@" -fdirectives-only 2> "$err" || "$@" 2> "$err"
else
    "$@" 2> "$err"
fi
ec=$?
awk '
/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ { stop = 1 }
/^\.+ [^\/]/ && !end { started = 1; print $0 }       # an inclusion-stack line
!/^\.+ / && started { end = 1 }                      # first line after the stack
!/^\.+ / && (!stop || (!/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ && !/^[a-zA-Z0-9\.\/\+_-]+$/)) { print $0 > "/dev/stderr" }
' "$err" > "$out.new"
# write-if-changed: keep $out's mtime when the inclusion stack is unchanged, so
# ninja's `restat` can prune the inclusion check on recompiles that don't alter
# the set of included headers. See issue #1161.
if [ -f "$out" ] && cmp -s "$out.new" "$out"; then
    rm -f "$out.new"
else
    mv "$out.new" "$out"
fi
rm -f "$err"
exit $ec
